#Image id 4 - cam 1

order_in_json_to_unified_id = dict(zip(range(1, 33), range(39, 71)))

order_in_json_to_unified_id.update(dict(zip(range(33, 57), range(71, 95))))

order_in_json_to_unified_id.update(dict(zip(range(57, 81), range(95, 119))))

order_in_json_to_unified_id.update(dict(zip(range(81, 91), range(119, 129))))

# Image id 5 - cam 2

order_in_json_to_unified_id.update(dict(zip(range(91, 107), range(0, 16))))

order_in_json_to_unified_id.update(dict(zip(range(107, 130), range(16, 39))))

order_in_json_to_unified_id.update(dict(zip(range(130, 160), range(40, 70))))

order_in_json_to_unified_id.update({160: 39, 161: 70})

# Image id 6 - cam 3

order_in_json_to_unified_id.update(dict(zip(range(162, 170), range(126, 118, -1))))

order_in_json_to_unified_id.update({170: 82, 171: 83, 172: 81, 173: 84, 174: 80, 175: 85,
                                    176: 86, 177: 79, 178: 87, 179: 78, 180: 88, 181: 77,
                                    182: 89, 183: 76, 184: 90, 185: 75, 186: 91, 187: 74,
                                    188: 92, 189: 93, 190: 73, 191: 72, 192: 94, 193: 71})

order_in_json_to_unified_id.update({194: 106, 195: 105, 196: 108, 197: 104, 198: 109, 199: 103,
                                    200: 110, 201: 102, 202: 111, 203: 101, 204: 112, 205: 100,
                                    206: 113, 207: 99, 208: 114, 209: 98, 210: 115, 211: 97,
                                    212: 116, 213: 96, 214: 117, 215: 95, 216: 118})

cam_to_space_id = {"cam_1": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90],
                   "cam_2": [91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161],
                   "cam_3": [162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216]}

cam_to_unified_id = {k: list(map(lambda x: order_in_json_to_unified_id[x], v)) for k, v in cam_to_space_id.items()}

#### Format {space_id: {"cam_1": polygon_in_cam_1, "cam_2": polygon_in_cam_2, "cam_3": polygon_in_cam_3},...}

unified_id_and_adjacency_ids = {0: {"adjacencies": {"eastern_adjacency": None,
                                                    "western_adjacency": 1,
                                                    "southern_adjacency": None,
                                                    "northern_adjacency": None,
                                                    "south_east_adjacency": None,
                                                    "south_west_adjacency": None,
                                                    "north_west_adjacency": None,
                                                    "north_east_adjacency": None}},
                                1: {"adjacencies": {"eastern_adjacency": 0,
                                                    "western_adjacency": 2,
                                                    "southern_adjacency": None,
                                                    "northern_adjacency": None,
                                                    "south_east_adjacency": None,
                                                    "south_west_adjacency": None,
                                                    "north_west_adjacency": None,
                                                    "north_east_adjacency": None}},
                                2: {"adjacencies": {"eastern_adjacency": 1,
                                                    "western_adjacency": 3,
                                                    "southern_adjacency": None,
                                                    "northern_adjacency": None,
                                                    "south_east_adjacency": None,
                                                    "south_west_adjacency": None,
                                                    "north_west_adjacency": None,
                                                    "north_east_adjacency": None}},
                                3: {"adjacencies": {"eastern_adjacency": 2,
                                                    "western_adjacency": 4,
                                                    "southern_adjacency": None,
                                                    "northern_adjacency": None,
                                                    "south_east_adjacency": None,
                                                    "south_west_adjacency": None,
                                                    "north_west_adjacency": None,
                                                    "north_east_adjacency": None}},
                                4: {"adjacencies": {"eastern_adjacency": 3,
                                                    "western_adjacency": 5,
                                                    "southern_adjacency": None,
                                                    "northern_adjacency": None,
                                                    "south_east_adjacency": None,
                                                    "south_west_adjacency": None,
                                                    "north_west_adjacency": None,
                                                    "north_east_adjacency": None}},
                                5: {"adjacencies": {"eastern_adjacency": 4,
                                                    "western_adjacency": 6,
                                                    "southern_adjacency": None,
                                                    "northern_adjacency": None,
                                                    "south_east_adjacency": None,
                                                    "south_west_adjacency": None,
                                                    "north_west_adjacency": None,
                                                    "north_east_adjacency": None}},
                                6: {"adjacencies": {"eastern_adjacency": 5,
                                                    "western_adjacency": 7,
                                                    "southern_adjacency": None,
                                                    "northern_adjacency": None,
                                                    "south_east_adjacency": None,
                                                    "south_west_adjacency": None,
                                                    "north_west_adjacency": None,
                                                    "north_east_adjacency": None}},
                                7: {"adjacencies": {"eastern_adjacency": 6,
                                                    "western_adjacency": 8,
                                                    "southern_adjacency": None,
                                                    "northern_adjacency": None,
                                                    "south_east_adjacency": None,
                                                    "south_west_adjacency": None,
                                                    "north_west_adjacency": None,
                                                    "north_east_adjacency": None}},
                                8: {"adjacencies": {"eastern_adjacency": 7,
                                                    "western_adjacency": 9,
                                                    "southern_adjacency": None,
                                                    "northern_adjacency": None,
                                                    "south_east_adjacency": None,
                                                    "south_west_adjacency": None,
                                                    "north_west_adjacency": None,
                                                    "north_east_adjacency": None}},
                                9: {"adjacencies": {"eastern_adjacency": 8,
                                                    "western_adjacency": 10,
                                                    "southern_adjacency": None,
                                                    "northern_adjacency": None,
                                                    "south_east_adjacency": None,
                                                    "south_west_adjacency": None,
                                                    "north_west_adjacency": None,
                                                    "north_east_adjacency": None}},
                                10: {"adjacencies": {"eastern_adjacency": 9,
                                                    "western_adjacency": 11,
                                                    "southern_adjacency": None,
                                                    "northern_adjacency": None,
                                                    "south_east_adjacency": None,
                                                    "south_west_adjacency": None,
                                                    "north_west_adjacency": None,
                                                    "north_east_adjacency": None}},
                                11: {"adjacencies": {"eastern_adjacency": 10,
                                                    "western_adjacency": 12,
                                                    "southern_adjacency": None,
                                                    "northern_adjacency": None,
                                                    "south_east_adjacency": None,
                                                    "south_west_adjacency": None,
                                                    "north_west_adjacency": None,
                                                    "north_east_adjacency": None}},
                                12: {"adjacencies": {"eastern_adjacency": 11,
                                                    "western_adjacency": 13,
                                                    "southern_adjacency": None,
                                                    "northern_adjacency": None,
                                                    "south_east_adjacency": None,
                                                    "south_west_adjacency": None,
                                                    "north_west_adjacency": None,
                                                    "north_east_adjacency": None}},
                                13: {"adjacencies": {"eastern_adjacency": 12,
                                                    "western_adjacency": 14,
                                                    "southern_adjacency": None,
                                                    "northern_adjacency": None,
                                                    "south_east_adjacency": None,
                                                    "south_west_adjacency": None,
                                                    "north_west_adjacency": None,
                                                    "north_east_adjacency": None}},
                                14: {"adjacencies": {"eastern_adjacency": 13,
                                                    "western_adjacency": 15,
                                                    "southern_adjacency": None,
                                                    "northern_adjacency": None,
                                                    "south_east_adjacency": None,
                                                    "south_west_adjacency": None,
                                                    "north_west_adjacency": None,
                                                    "north_east_adjacency": None}},
                                15: {"adjacencies": {"eastern_adjacency": 14,
                                                    "western_adjacency": None,
                                                    "southern_adjacency": None,
                                                    "northern_adjacency": None,
                                                    "south_east_adjacency": None,
                                                    "south_west_adjacency": None,
                                                    "north_west_adjacency": None,
                                                    "north_east_adjacency": None}},
                                16: {"adjacencies": {"eastern_adjacency": 17,
                                                    "western_adjacency": None,
                                                    "southern_adjacency": None,
                                                    "northern_adjacency": 38,
                                                    "south_east_adjacency": None,
                                                    "south_west_adjacency": None,
                                                    "north_west_adjacency": None,
                                                    "north_east_adjacency": 37}},
                                17: {"adjacencies": {"eastern_adjacency": 18,
                                                    "western_adjacency": 16,
                                                    "southern_adjacency": None,
                                                    "northern_adjacency": 37,
                                                    "south_east_adjacency": None,
                                                    "south_west_adjacency": None,
                                                    "north_west_adjacency": 38,
                                                    "north_east_adjacency": 36}},
                                18: {"adjacencies": {"eastern_adjacency": 19,
                                                     "western_adjacency": 17,
                                                     "southern_adjacency": None,
                                                     "northern_adjacency": 36,
                                                     "south_east_adjacency": None,
                                                     "south_west_adjacency": None,
                                                     "north_west_adjacency": 37,
                                                     "north_east_adjacency": 35}},
                                19: {"adjacencies": {"eastern_adjacency": 20,
                                                    "western_adjacency": 18,
                                                    "southern_adjacency": None,
                                                    "northern_adjacency": 35,
                                                    "south_east_adjacency": None,
                                                    "south_west_adjacency": None,
                                                    "north_west_adjacency": 36,
                                                    "north_east_adjacency": None}},
                                20: {"adjacencies": {"eastern_adjacency": 21,
                                                     "western_adjacency": 19,
                                                     "southern_adjacency": None,
                                                     "northern_adjacency": None,
                                                     "south_east_adjacency": None,
                                                     "south_west_adjacency": None,
                                                     "north_west_adjacency": 35,
                                                     "north_east_adjacency": 34}},
                                21: {"adjacencies": {"eastern_adjacency": 22,
                                                     "western_adjacency": 20,
                                                     "southern_adjacency": None,
                                                     "northern_adjacency": 34,
                                                     "south_east_adjacency": None,
                                                     "south_west_adjacency": None,
                                                     "north_west_adjacency": None,
                                                     "north_east_adjacency": 33}},
                                22: {"adjacencies": {"eastern_adjacency": 23,
                                                     "western_adjacency": 21,
                                                     "southern_adjacency": None,
                                                     "northern_adjacency": 33,
                                                     "south_east_adjacency": None,
                                                     "south_west_adjacency": None,
                                                     "north_west_adjacency": 34,
                                                     "north_east_adjacency": 32}},
                                23: {"adjacencies": {"eastern_adjacency": 24,
                                                     "western_adjacency": 22,
                                                     "southern_adjacency": None,
                                                     "northern_adjacency": 32,
                                                     "south_east_adjacency": None,
                                                     "south_west_adjacency": None,
                                                     "north_west_adjacency": 33,
                                                     "north_east_adjacency": 31}},
                                24: {"adjacencies": {"eastern_adjacency": 25,
                                                     "western_adjacency": 23,
                                                     "southern_adjacency": None,
                                                     "northern_adjacency": 31,
                                                     "south_east_adjacency": None,
                                                     "south_west_adjacency": None,
                                                     "north_west_adjacency": 32,
                                                     "north_east_adjacency": 30}},
                                25: {"adjacencies": {"eastern_adjacency": 26,
                                                     "western_adjacency": 24,
                                                     "southern_adjacency": None,
                                                     "northern_adjacency": 30,
                                                     "south_east_adjacency": None,
                                                     "south_west_adjacency": None,
                                                     "north_west_adjacency": 31,
                                                     "north_east_adjacency": 29}},
                                26: {"adjacencies": {"eastern_adjacency": 27,
                                                     "western_adjacency": 25,
                                                     "southern_adjacency": None,
                                                     "northern_adjacency": 29,
                                                     "south_east_adjacency": None,
                                                     "south_west_adjacency": None,
                                                     "north_west_adjacency": 30,
                                                     "north_east_adjacency": 28}},
                                27: {"adjacencies": {"eastern_adjacency": None,
                                                     "western_adjacency": 26,
                                                     "southern_adjacency": None,
                                                     "northern_adjacency": 28,
                                                     "south_east_adjacency": None,
                                                     "south_west_adjacency": None,
                                                     "north_west_adjacency": 29,
                                                     "north_east_adjacency": None}},
                                28: {"adjacencies": {"eastern_adjacency": None,
                                                     "western_adjacency": 29,
                                                     "southern_adjacency": 27,
                                                     "northern_adjacency": None,
                                                     "south_east_adjacency": None,
                                                     "south_west_adjacency": 26,
                                                     "north_west_adjacency": None,
                                                     "north_east_adjacency": None}},
                                29: {"adjacencies": {"eastern_adjacency": 28,
                                                     "western_adjacency": 30,
                                                     "southern_adjacency": 26,
                                                     "northern_adjacency": None,
                                                     "south_east_adjacency": 27,
                                                     "south_west_adjacency": 25,
                                                     "north_west_adjacency": None,
                                                     "north_east_adjacency": None}},
                                30: {"adjacencies": {"eastern_adjacency": 29,
                                                     "western_adjacency": 31,
                                                     "southern_adjacency": 25,
                                                     "northern_adjacency": None,
                                                     "south_east_adjacency": 26,
                                                     "south_west_adjacency": 24,
                                                     "north_west_adjacency": None,
                                                     "north_east_adjacency": None}},
                                31: {"adjacencies": {"eastern_adjacency": 30,
                                                     "western_adjacency": 32,
                                                     "southern_adjacency": 24,
                                                     "northern_adjacency": None,
                                                     "south_east_adjacency": 25,
                                                     "south_west_adjacency": 23,
                                                     "north_west_adjacency": None,
                                                     "north_east_adjacency": None}},
                                32: {"adjacencies": {"eastern_adjacency": 31,
                                                     "western_adjacency": 33,
                                                     "southern_adjacency": 23,
                                                     "northern_adjacency": None,
                                                     "south_east_adjacency": 24,
                                                     "south_west_adjacency": 22,
                                                     "north_west_adjacency": None,
                                                     "north_east_adjacency": None}},
                                33: {"adjacencies": {"eastern_adjacency": 32,
                                                     "western_adjacency": 34,
                                                     "southern_adjacency": 22,
                                                     "northern_adjacency": None,
                                                     "south_east_adjacency": 23,
                                                     "south_west_adjacency": 21,
                                                     "north_west_adjacency": None,
                                                     "north_east_adjacency": None}},
                                34: {"adjacencies": {"eastern_adjacency": 33,
                                                     "western_adjacency": None,
                                                     "southern_adjacency": 21,
                                                     "northern_adjacency": None,
                                                     "south_east_adjacency": 22,
                                                     "south_west_adjacency": 20,
                                                     "north_west_adjacency": None,
                                                     "north_east_adjacency": None}},
                                35: {"adjacencies": {"eastern_adjacency": None,
                                                     "western_adjacency": 36,
                                                     "southern_adjacency": 19,
                                                     "northern_adjacency": None,
                                                     "south_east_adjacency": 20,
                                                     "south_west_adjacency": 18,
                                                     "north_west_adjacency": None,
                                                     "north_east_adjacency": None}},
                                36: {"adjacencies": {"eastern_adjacency": 35,
                                                     "western_adjacency": 37,
                                                     "southern_adjacency": 18,
                                                     "northern_adjacency": None,
                                                     "south_east_adjacency": 19,
                                                     "south_west_adjacency": 17,
                                                     "north_west_adjacency": None,
                                                     "north_east_adjacency": None}},
                                37: {"adjacencies": {"eastern_adjacency": 36,
                                                     "western_adjacency": 38,
                                                     "southern_adjacency": 17,
                                                     "northern_adjacency": None,
                                                     "south_east_adjacency": 18,
                                                     "south_west_adjacency": 16,
                                                     "north_west_adjacency": None,
                                                     "north_east_adjacency": None}},
                                38: {"adjacencies": {"eastern_adjacency": 37,
                                                     "western_adjacency": None,
                                                     "southern_adjacency": 16,
                                                     "northern_adjacency": None,
                                                     "south_east_adjacency": 17,
                                                     "south_west_adjacency": None,
                                                     "north_west_adjacency": None,
                                                     "north_east_adjacency": None}},
                                39: {"adjacencies": {"eastern_adjacency": 40,
                                                     "western_adjacency": None,
                                                     "southern_adjacency": None,
                                                     "northern_adjacency": 70,
                                                     "south_east_adjacency": None,
                                                     "south_west_adjacency": None,
                                                     "north_west_adjacency": None,
                                                     "north_east_adjacency": 69}},
                                40: {"adjacencies": {"eastern_adjacency": 41,
                                                     "western_adjacency": 39,
                                                     "southern_adjacency": None,
                                                     "northern_adjacency": 69,
                                                     "south_east_adjacency": None,
                                                     "south_west_adjacency": None,
                                                     "north_west_adjacency": 70,
                                                     "north_east_adjacency": 68}},
                                41: {"adjacencies": {"eastern_adjacency": 42,
                                                     "western_adjacency": 40,
                                                     "southern_adjacency": None,
                                                     "northern_adjacency": 68,
                                                     "south_east_adjacency": None,
                                                     "south_west_adjacency": None,
                                                     "north_west_adjacency": 69,
                                                     "north_east_adjacency": 67}},
                                42: {"adjacencies": {"eastern_adjacency": 43,
                                                     "western_adjacency": 41,
                                                     "southern_adjacency": None,
                                                     "northern_adjacency": 67,
                                                     "south_east_adjacency": None,
                                                     "south_west_adjacency": None,
                                                     "north_west_adjacency": 68,
                                                     "north_east_adjacency": 66}},
                                43: {"adjacencies": {"eastern_adjacency": 44,
                                                     "western_adjacency": 42,
                                                     "southern_adjacency": None,
                                                     "northern_adjacency": 66,
                                                     "south_east_adjacency": None,
                                                     "south_west_adjacency": None,
                                                     "north_west_adjacency": 67,
                                                     "north_east_adjacency": 65}},
                                44: {"adjacencies": {"eastern_adjacency": 45,
                                                     "western_adjacency": 43,
                                                     "southern_adjacency": None,
                                                     "northern_adjacency": 65,
                                                     "south_east_adjacency": None,
                                                     "south_west_adjacency": None,
                                                     "north_west_adjacency": 66,
                                                     "north_east_adjacency": 64}},
                                45: {"adjacencies": {"eastern_adjacency": 46,
                                                     "western_adjacency": 44,
                                                     "southern_adjacency": None,
                                                     "northern_adjacency": 64,
                                                     "south_east_adjacency": None,
                                                     "south_west_adjacency": None,
                                                     "north_west_adjacency": 65,
                                                     "north_east_adjacency": 63}},
                                46: {"adjacencies": {"eastern_adjacency": 47,
                                                     "western_adjacency": 45,
                                                     "southern_adjacency": None,
                                                     "northern_adjacency": 63,
                                                     "south_east_adjacency": None,
                                                     "south_west_adjacency": None,
                                                     "north_west_adjacency": 64,
                                                     "north_east_adjacency": 62}},
                                47: {"adjacencies": {"eastern_adjacency": 48,
                                                     "western_adjacency": 46,
                                                     "southern_adjacency": None,
                                                     "northern_adjacency": 62,
                                                     "south_east_adjacency": None,
                                                     "south_west_adjacency": None,
                                                     "north_west_adjacency": 63,
                                                     "north_east_adjacency": 61}},
                                48: {"adjacencies": {"eastern_adjacency": 49,
                                                     "western_adjacency": 47,
                                                     "southern_adjacency": None,
                                                     "northern_adjacency": 61,
                                                     "south_east_adjacency": None,
                                                     "south_west_adjacency": None,
                                                     "north_west_adjacency": 62,
                                                     "north_east_adjacency": 60}},
                                49: {"adjacencies": {"eastern_adjacency": 50,
                                                     "western_adjacency": 48,
                                                     "southern_adjacency": None,
                                                     "northern_adjacency": 60,
                                                     "south_east_adjacency": None,
                                                     "south_west_adjacency": None,
                                                     "north_west_adjacency": 61,
                                                     "north_east_adjacency": 59}},
                                50: {"adjacencies": {"eastern_adjacency": 51,
                                                     "western_adjacency": 49,
                                                     "southern_adjacency": None,
                                                     "northern_adjacency": 59,
                                                     "south_east_adjacency": None,
                                                     "south_west_adjacency": None,
                                                     "north_west_adjacency": 60,
                                                     "north_east_adjacency": 58}},
                                51: {"adjacencies": {"eastern_adjacency": 52,
                                                     "western_adjacency": 50,
                                                     "southern_adjacency": None,
                                                     "northern_adjacency": 58,
                                                     "south_east_adjacency": None,
                                                     "south_west_adjacency": None,
                                                     "north_west_adjacency": 59,
                                                     "north_east_adjacency": 57}},
                                52: {"adjacencies": {"eastern_adjacency": 53,
                                                     "western_adjacency": 51,
                                                     "southern_adjacency": None,
                                                     "northern_adjacency": 57,
                                                     "south_east_adjacency": None,
                                                     "south_west_adjacency": None,
                                                     "north_west_adjacency": 58,
                                                     "north_east_adjacency": 56}},
                                53: {"adjacencies": {"eastern_adjacency": 54,
                                                     "western_adjacency": 52,
                                                     "southern_adjacency": None,
                                                     "northern_adjacency": 56,
                                                     "south_east_adjacency": None,
                                                     "south_west_adjacency": None,
                                                     "north_west_adjacency": 57,
                                                     "north_east_adjacency": 55}},
                                54: {"adjacencies": {"eastern_adjacency": None,
                                                     "western_adjacency": 53,
                                                     "southern_adjacency": None,
                                                     "northern_adjacency": 55,
                                                     "south_east_adjacency": None,
                                                     "south_west_adjacency": None,
                                                     "north_west_adjacency": 56,
                                                     "north_east_adjacency": None}},
                                55: {"adjacencies": {"eastern_adjacency": None,
                                                     "western_adjacency": 56,
                                                     "southern_adjacency": 54,
                                                     "northern_adjacency": None,
                                                     "south_east_adjacency": None,
                                                     "south_west_adjacency": 53,
                                                     "north_west_adjacency": None,
                                                     "north_east_adjacency": None}},
                                56: {"adjacencies": {"eastern_adjacency": 55,
                                                     "western_adjacency": 57,
                                                     "southern_adjacency": 53,
                                                     "northern_adjacency": None,
                                                     "south_east_adjacency": 54,
                                                     "south_west_adjacency": 52,
                                                     "north_west_adjacency": None,
                                                     "north_east_adjacency": None}},
                                57: {"adjacencies": {"eastern_adjacency": 56,
                                                     "western_adjacency": 59,
                                                     "southern_adjacency": 52,
                                                     "northern_adjacency": None,
                                                     "south_east_adjacency": 53,
                                                     "south_west_adjacency": 51,
                                                     "north_west_adjacency": None,
                                                     "north_east_adjacency": None}},
                                58: {"adjacencies": {"eastern_adjacency": 57,
                                                     "western_adjacency": 59,
                                                     "southern_adjacency": 51,
                                                     "northern_adjacency": None,
                                                     "south_east_adjacency": 52,
                                                     "south_west_adjacency": 50,
                                                     "north_west_adjacency": None,
                                                     "north_east_adjacency": None}},
                                59: {"adjacencies": {"eastern_adjacency": 58,
                                                     "western_adjacency": 60,
                                                     "southern_adjacency": 50,
                                                     "northern_adjacency": None,
                                                     "south_east_adjacency": 51,
                                                     "south_west_adjacency": 49,
                                                     "north_west_adjacency": None,
                                                     "north_east_adjacency": None}},
                                60: {"adjacencies": {"eastern_adjacency": 59,
                                                     "western_adjacency": 61,
                                                     "southern_adjacency": 49,
                                                     "northern_adjacency": None,
                                                     "south_east_adjacency": 50,
                                                     "south_west_adjacency": 48,
                                                     "north_west_adjacency": None,
                                                     "north_east_adjacency": None}},
                                61: {"adjacencies": {"eastern_adjacency": 60,
                                                     "western_adjacency": 62,
                                                     "southern_adjacency": 48,
                                                     "northern_adjacency": None,
                                                     "south_east_adjacency": 49,
                                                     "south_west_adjacency": 47,
                                                     "north_west_adjacency": None,
                                                     "north_east_adjacency": None}},
                                62: {"adjacencies": {"eastern_adjacency": 61,
                                                     "western_adjacency": 63,
                                                     "southern_adjacency": 47,
                                                     "northern_adjacency": None,
                                                     "south_east_adjacency": 48,
                                                     "south_west_adjacency": 46,
                                                     "north_west_adjacency": None,
                                                     "north_east_adjacency": None}},
                                63: {"adjacencies": {"eastern_adjacency": 62,
                                                     "western_adjacency": 64,
                                                     "southern_adjacency": 46,
                                                     "northern_adjacency": None,
                                                     "south_east_adjacency": 47,
                                                     "south_west_adjacency": 45,
                                                     "north_west_adjacency": None,
                                                     "north_east_adjacency": None}},
                                64: {"adjacencies": {"eastern_adjacency": 63,
                                                     "western_adjacency": 65,
                                                     "southern_adjacency": 45,
                                                     "northern_adjacency": None,
                                                     "south_east_adjacency": 46,
                                                     "south_west_adjacency": 44,
                                                     "north_west_adjacency": None,
                                                     "north_east_adjacency": None}},
                                65: {"adjacencies": {"eastern_adjacency": 64,
                                                     "western_adjacency": 66,
                                                     "southern_adjacency": 44,
                                                     "northern_adjacency": None,
                                                     "south_east_adjacency": 45,
                                                     "south_west_adjacency": 43,
                                                     "north_west_adjacency": None,
                                                     "north_east_adjacency": None}},
                                66: {"adjacencies": {"eastern_adjacency": 65,
                                                     "western_adjacency": 67,
                                                     "southern_adjacency": 43,
                                                     "northern_adjacency": None,
                                                     "south_east_adjacency": 44,
                                                     "south_west_adjacency": 42,
                                                     "north_west_adjacency": None,
                                                     "north_east_adjacency": None}},
                                67: {"adjacencies": {"eastern_adjacency": 66,
                                                     "western_adjacency": 68,
                                                     "southern_adjacency": 42,
                                                     "northern_adjacency": None,
                                                     "south_east_adjacency": 43,
                                                     "south_west_adjacency": 42,
                                                     "north_west_adjacency": None,
                                                     "north_east_adjacency": None}},
                                68: {"adjacencies": {"eastern_adjacency": 67,
                                                     "western_adjacency": 69,
                                                     "southern_adjacency": 41,
                                                     "northern_adjacency": None,
                                                     "south_east_adjacency": 42,
                                                     "south_west_adjacency": 40,
                                                     "north_west_adjacency": None,
                                                     "north_east_adjacency": None}},
                                69: {"adjacencies": {"eastern_adjacency": 68,
                                                     "western_adjacency": 70,
                                                     "southern_adjacency": 40,
                                                     "northern_adjacency": None,
                                                     "south_east_adjacency": 41,
                                                     "south_west_adjacency": 39,
                                                     "north_west_adjacency": None,
                                                     "north_east_adjacency": None}},
                                70: {"adjacencies": {"eastern_adjacency": 69,
                                                     "western_adjacency": None,
                                                     "southern_adjacency": 39,
                                                     "northern_adjacency": None,
                                                     "south_east_adjacency": 40,
                                                     "south_west_adjacency": None,
                                                     "north_west_adjacency": None,
                                                     "north_east_adjacency": None}},
                                71: {"adjacencies": {"eastern_adjacency": 72,
                                                     "western_adjacency": None,
                                                     "southern_adjacency": None,
                                                     "northern_adjacency": 94,
                                                     "south_east_adjacency": None,
                                                     "south_west_adjacency": None,
                                                     "north_west_adjacency": None,
                                                     "north_east_adjacency": 93}},
                                72: {"adjacencies": {"eastern_adjacency": 73,
                                                     "western_adjacency": 71,
                                                     "southern_adjacency": None,
                                                     "northern_adjacency": 93,
                                                     "south_east_adjacency": None,
                                                     "south_west_adjacency": None,
                                                     "north_west_adjacency": 94,
                                                     "north_east_adjacency": 92}},
                                73: {"adjacencies": {"eastern_adjacency": 74,
                                                     "western_adjacency": 72,
                                                     "southern_adjacency": None,
                                                     "northern_adjacency": 92,
                                                     "south_east_adjacency": None,
                                                     "south_west_adjacency": None,
                                                     "north_west_adjacency": 93,
                                                     "north_east_adjacency": 91}},
                                74: {"adjacencies": {"eastern_adjacency": 75,
                                                     "western_adjacency": 73,
                                                     "southern_adjacency": None,
                                                     "northern_adjacency": 91,
                                                     "south_east_adjacency": None,
                                                     "south_west_adjacency": None,
                                                     "north_west_adjacency": 92,
                                                     "north_east_adjacency": 90}},
                                75: {"adjacencies": {"eastern_adjacency": 76,
                                                     "western_adjacency": 74,
                                                     "southern_adjacency": None,
                                                     "northern_adjacency": 90,
                                                     "south_east_adjacency": None,
                                                     "south_west_adjacency": None,
                                                     "north_west_adjacency": 91,
                                                     "north_east_adjacency": 89}},
                                76: {"adjacencies": {"eastern_adjacency": 77,
                                                     "western_adjacency": 75,
                                                     "southern_adjacency": None,
                                                     "northern_adjacency": 89,
                                                     "south_east_adjacency": None,
                                                     "south_west_adjacency": None,
                                                     "north_west_adjacency": 90,
                                                     "north_east_adjacency": 88}},
                                77: {"adjacencies": {"eastern_adjacency": 78,
                                                     "western_adjacency": 76,
                                                     "southern_adjacency": None,
                                                     "northern_adjacency": 88,
                                                     "south_east_adjacency": None,
                                                     "south_west_adjacency": None,
                                                     "north_west_adjacency": 89,
                                                     "north_east_adjacency": 87}},
                                78: {"adjacencies": {"eastern_adjacency": 79,
                                                     "western_adjacency": 77,
                                                     "southern_adjacency": None,
                                                     "northern_adjacency": 87,
                                                     "south_east_adjacency": None,
                                                     "south_west_adjacency": None,
                                                     "north_west_adjacency": 88,
                                                     "north_east_adjacency": 86}},
                                79: {"adjacencies": {"eastern_adjacency": 80,
                                                     "western_adjacency": 78,
                                                     "southern_adjacency": None,
                                                     "northern_adjacency": 86,
                                                     "south_east_adjacency": None,
                                                     "south_west_adjacency": None,
                                                     "north_west_adjacency": 87,
                                                     "north_east_adjacency": 85}},
                                80: {"adjacencies": {"eastern_adjacency": 81,
                                                     "western_adjacency": 79,
                                                     "southern_adjacency": None,
                                                     "northern_adjacency": 85,
                                                     "south_east_adjacency": None,
                                                     "south_west_adjacency": None,
                                                     "north_west_adjacency": 86,
                                                     "north_east_adjacency": 84}},
                                81: {"adjacencies": {"eastern_adjacency": 82,
                                                     "western_adjacency": 80,
                                                     "southern_adjacency": None,
                                                     "northern_adjacency": 84,
                                                     "south_east_adjacency": None,
                                                     "south_west_adjacency": None,
                                                     "north_west_adjacency": 85,
                                                     "north_east_adjacency": 83}},
                                82: {"adjacencies": {"eastern_adjacency": None,
                                                     "western_adjacency": 81,
                                                     "southern_adjacency": None,
                                                     "northern_adjacency": 83,
                                                     "south_east_adjacency": None,
                                                     "south_west_adjacency": None,
                                                     "north_west_adjacency": 84,
                                                     "north_east_adjacency": None}},
                                83: {"adjacencies": {"eastern_adjacency": None,
                                                     "western_adjacency": 84,
                                                     "southern_adjacency": 82,
                                                     "northern_adjacency": None,
                                                     "south_east_adjacency": None,
                                                     "south_west_adjacency": 81,
                                                     "north_west_adjacency": None,
                                                     "north_east_adjacency": None}},
                                84: {"adjacencies": {"eastern_adjacency": 83,
                                                     "western_adjacency": 85,
                                                     "southern_adjacency": 81,
                                                     "northern_adjacency": None,
                                                     "south_east_adjacency": 82,
                                                     "south_west_adjacency": 80,
                                                     "north_west_adjacency": None,
                                                     "north_east_adjacency": None}},
                                85: {"adjacencies": {"eastern_adjacency": 84,
                                                     "western_adjacency": 86,
                                                     "southern_adjacency": 80,
                                                     "northern_adjacency": None,
                                                     "south_east_adjacency": 81,
                                                     "south_west_adjacency": 79,
                                                     "north_west_adjacency": None,
                                                     "north_east_adjacency": None}},
                                86: {"adjacencies": {"eastern_adjacency": 85,
                                                     "western_adjacency": 87,
                                                     "southern_adjacency": 79,
                                                     "northern_adjacency": None,
                                                     "south_east_adjacency": 80,
                                                     "south_west_adjacency": 78,
                                                     "north_west_adjacency": None,
                                                     "north_east_adjacency": None}},
                                87: {"adjacencies": {"eastern_adjacency": 86,
                                                     "western_adjacency": 88,
                                                     "southern_adjacency": 78,
                                                     "northern_adjacency": None,
                                                     "south_east_adjacency": 79,
                                                     "south_west_adjacency": 77,
                                                     "north_west_adjacency": None,
                                                     "north_east_adjacency": None}},
                                88: {"adjacencies": {"eastern_adjacency": 87,
                                                     "western_adjacency": 89,
                                                     "southern_adjacency": 77,
                                                     "northern_adjacency": None,
                                                     "south_east_adjacency": 78,
                                                     "south_west_adjacency": 76,
                                                     "north_west_adjacency": None,
                                                     "north_east_adjacency": None}},
                                89: {"adjacencies": {"eastern_adjacency": 88,
                                                     "western_adjacency": 90,
                                                     "southern_adjacency": 76,
                                                     "northern_adjacency": None,
                                                     "south_east_adjacency": 77,
                                                     "south_west_adjacency": 75,
                                                     "north_west_adjacency": None,
                                                     "north_east_adjacency": None}},
                                90: {"adjacencies": {"eastern_adjacency": 89,
                                                     "western_adjacency": 91,
                                                     "southern_adjacency": 75,
                                                     "northern_adjacency": None,
                                                     "south_east_adjacency": 76,
                                                     "south_west_adjacency": 74,
                                                     "north_west_adjacency": None,
                                                     "north_east_adjacency": None}},
                                91: {"adjacencies": {"eastern_adjacency": 90,
                                                     "western_adjacency": 92,
                                                     "southern_adjacency": 74,
                                                     "northern_adjacency": None,
                                                     "south_east_adjacency": 75,
                                                     "south_west_adjacency": 73,
                                                     "north_west_adjacency": None,
                                                     "north_east_adjacency": None}},
                                92: {"adjacencies": {"eastern_adjacency": 91,
                                                     "western_adjacency": 93,
                                                     "southern_adjacency": 73,
                                                     "northern_adjacency": None,
                                                     "south_east_adjacency": 74,
                                                     "south_west_adjacency": 72,
                                                     "north_west_adjacency": None,
                                                     "north_east_adjacency": None}},
                                93: {"adjacencies": {"eastern_adjacency": 92,
                                                     "western_adjacency": 94,
                                                     "southern_adjacency": 72,
                                                     "northern_adjacency": None,
                                                     "south_east_adjacency": 73,
                                                     "south_west_adjacency": 71,
                                                     "north_west_adjacency": None,
                                                     "north_east_adjacency": None}},
                                94: {"adjacencies": {"eastern_adjacency": 93,
                                                     "western_adjacency": None,
                                                     "southern_adjacency": 71,
                                                     "northern_adjacency": None,
                                                     "south_east_adjacency": 72,
                                                     "south_west_adjacency": None,
                                                     "north_west_adjacency": None,
                                                     "north_east_adjacency": None}},
                                95: {"adjacencies": {"eastern_adjacency": 96,
                                                     "western_adjacency": None,
                                                     "southern_adjacency": None,
                                                     "northern_adjacency": 118,
                                                     "south_east_adjacency": None,
                                                     "south_west_adjacency": None,
                                                     "north_west_adjacency": None,
                                                     "north_east_adjacency": 117}},
                                96: {"adjacencies": {"eastern_adjacency": 97,
                                                     "western_adjacency": 95,
                                                     "southern_adjacency": None,
                                                     "northern_adjacency": 117,
                                                     "south_east_adjacency": None,
                                                     "south_west_adjacency": None,
                                                     "north_west_adjacency": 118,
                                                     "north_east_adjacency": 116}},
                                97: {"adjacencies": {"eastern_adjacency": 98,
                                                     "western_adjacency": 96,
                                                     "southern_adjacency": None,
                                                     "northern_adjacency": 116,
                                                     "south_east_adjacency": None,
                                                     "south_west_adjacency": None,
                                                     "north_west_adjacency": 117,
                                                     "north_east_adjacency": 115}},
                                98: {"adjacencies": {"eastern_adjacency": 99,
                                                     "western_adjacency": 97,
                                                     "southern_adjacency": None,
                                                     "northern_adjacency": 115,
                                                     "south_east_adjacency": None,
                                                     "south_west_adjacency": None,
                                                     "north_west_adjacency": 116,
                                                     "north_east_adjacency": 114}},
                                99: {"adjacencies": {"eastern_adjacency": 100,
                                                     "western_adjacency": 98,
                                                     "southern_adjacency": None,
                                                     "northern_adjacency": 114,
                                                     "south_east_adjacency": None,
                                                     "south_west_adjacency": None,
                                                     "north_west_adjacency": 115,
                                                     "north_east_adjacency": 113}},
                                100: {"adjacencies": {"eastern_adjacency": 101,
                                                     "western_adjacency": 99,
                                                     "southern_adjacency": None,
                                                     "northern_adjacency": 113,
                                                     "south_east_adjacency": None,
                                                     "south_west_adjacency": None,
                                                     "north_west_adjacency": 114,
                                                     "north_east_adjacency": 112}},
                                101: {"adjacencies": {"eastern_adjacency": 102,
                                                     "western_adjacency": 100,
                                                     "southern_adjacency": None,
                                                     "northern_adjacency": 112,
                                                     "south_east_adjacency": None,
                                                     "south_west_adjacency": None,
                                                     "north_west_adjacency": 113,
                                                     "north_east_adjacency": 111}},
                                102: {"adjacencies": {"eastern_adjacency": 103,
                                                     "western_adjacency": 101,
                                                     "southern_adjacency": None,
                                                     "northern_adjacency": 111,
                                                     "south_east_adjacency": None,
                                                     "south_west_adjacency": None,
                                                     "north_west_adjacency": 112,
                                                     "north_east_adjacency": 110}},
                                103: {"adjacencies": {"eastern_adjacency": 104,
                                                     "western_adjacency": 102,
                                                     "southern_adjacency": None,
                                                     "northern_adjacency": 110,
                                                     "south_east_adjacency": None,
                                                     "south_west_adjacency": None,
                                                     "north_west_adjacency": 111,
                                                     "north_east_adjacency": 109}},
                                104: {"adjacencies": {"eastern_adjacency": 105,
                                                     "western_adjacency": 103,
                                                     "southern_adjacency": None,
                                                     "northern_adjacency": 109,
                                                     "south_east_adjacency": None,
                                                     "south_west_adjacency": None,
                                                     "north_west_adjacency": 110,
                                                     "north_east_adjacency": 108}},
                                105: {"adjacencies": {"eastern_adjacency": 106,
                                                     "western_adjacency": 104,
                                                     "southern_adjacency": None,
                                                     "northern_adjacency": 108,
                                                     "south_east_adjacency": None,
                                                     "south_west_adjacency": None,
                                                     "north_west_adjacency": 109,
                                                     "north_east_adjacency": 107}},
                                106: {"adjacencies": {"eastern_adjacency": None,
                                                     "western_adjacency": 105,
                                                     "southern_adjacency": None,
                                                     "northern_adjacency": 107,
                                                     "south_east_adjacency": None,
                                                     "south_west_adjacency": None,
                                                     "north_west_adjacency": 108,
                                                     "north_east_adjacency": None}},
                                107: {"adjacencies": {"eastern_adjacency": None,
                                                     "western_adjacency": 108,
                                                     "southern_adjacency": 106,
                                                     "northern_adjacency": None,
                                                     "south_east_adjacency": None,
                                                     "south_west_adjacency": 105,
                                                     "north_west_adjacency": None,
                                                     "north_east_adjacency": None}},
                                108: {"adjacencies": {"eastern_adjacency": 107,
                                                     "western_adjacency": 109,
                                                     "southern_adjacency": 105,
                                                     "northern_adjacency": None,
                                                     "south_east_adjacency": 106,
                                                     "south_west_adjacency": 104,
                                                     "north_west_adjacency": None,
                                                     "north_east_adjacency": None}},
                                109: {"adjacencies": {"eastern_adjacency": 108,
                                                     "western_adjacency": 110,
                                                     "southern_adjacency": 104,
                                                     "northern_adjacency": None,
                                                     "south_east_adjacency": 105,
                                                     "south_west_adjacency": 103,
                                                     "north_west_adjacency": None,
                                                     "north_east_adjacency": None}},
                                110: {"adjacencies": {"eastern_adjacency": 109,
                                                     "western_adjacency": 111,
                                                     "southern_adjacency": 103,
                                                     "northern_adjacency": None,
                                                     "south_east_adjacency": 104,
                                                     "south_west_adjacency": 102,
                                                     "north_west_adjacency": None,
                                                     "north_east_adjacency": None}},
                                111: {"adjacencies": {"eastern_adjacency": 110,
                                                     "western_adjacency": 112,
                                                     "southern_adjacency": 102,
                                                     "northern_adjacency": None,
                                                     "south_east_adjacency": 103,
                                                     "south_west_adjacency": 101,
                                                     "north_west_adjacency": None,
                                                     "north_east_adjacency": None}},
                                112: {"adjacencies": {"eastern_adjacency": 111,
                                                     "western_adjacency": 113,
                                                     "southern_adjacency": 101,
                                                     "northern_adjacency": None,
                                                     "south_east_adjacency": 102,
                                                     "south_west_adjacency": 100,
                                                     "north_west_adjacency": None,
                                                     "north_east_adjacency": None}},
                                113: {"adjacencies": {"eastern_adjacency": 112,
                                                     "western_adjacency": 114,
                                                     "southern_adjacency": 100,
                                                     "northern_adjacency": None,
                                                     "south_east_adjacency": 101,
                                                     "south_west_adjacency": 99,
                                                     "north_west_adjacency": None,
                                                     "north_east_adjacency": None}},
                                114: {"adjacencies": {"eastern_adjacency": 113,
                                                     "western_adjacency": 115,
                                                     "southern_adjacency": 99,
                                                     "northern_adjacency": None,
                                                     "south_east_adjacency": 100,
                                                     "south_west_adjacency": 98,
                                                     "north_west_adjacency": None,
                                                     "north_east_adjacency": None}},
                                115: {"adjacencies": {"eastern_adjacency": 114,
                                                     "western_adjacency": 116,
                                                     "southern_adjacency": 98,
                                                     "northern_adjacency": None,
                                                     "south_east_adjacency": 99,
                                                     "south_west_adjacency": 97,
                                                     "north_west_adjacency": None,
                                                     "north_east_adjacency": None}},
                                116: {"adjacencies": {"eastern_adjacency": 115,
                                                     "western_adjacency": 117,
                                                     "southern_adjacency": 97,
                                                     "northern_adjacency": None,
                                                     "south_east_adjacency": 98,
                                                     "south_west_adjacency": 96,
                                                     "north_west_adjacency": None,
                                                     "north_east_adjacency": None}},
                                117: {"adjacencies": {"eastern_adjacency": 116,
                                                     "western_adjacency": 118,
                                                     "southern_adjacency": 96,
                                                     "northern_adjacency": None,
                                                     "south_east_adjacency": 97,
                                                     "south_west_adjacency": 95,
                                                     "north_west_adjacency": None,
                                                     "north_east_adjacency": None}},
                                118: {"adjacencies": {"eastern_adjacency": 117,
                                                     "western_adjacency": None,
                                                     "southern_adjacency": 95,
                                                     "northern_adjacency": None,
                                                     "south_east_adjacency": 96,
                                                     "south_west_adjacency": None,
                                                     "north_west_adjacency": None,
                                                     "north_east_adjacency": None}},
                                119: {"adjacencies": {"eastern_adjacency": None,
                                                     "western_adjacency": None,
                                                     "southern_adjacency": 120,
                                                     "northern_adjacency": None,
                                                     "south_east_adjacency": None,
                                                     "south_west_adjacency": None,
                                                     "north_west_adjacency": None,
                                                     "north_east_adjacency": None}},
                                120: {"adjacencies": {"eastern_adjacency": None,
                                                     "western_adjacency": None,
                                                     "southern_adjacency": 121,
                                                     "northern_adjacency": 119,
                                                     "south_east_adjacency": None,
                                                     "south_west_adjacency": None,
                                                     "north_west_adjacency": None,
                                                     "north_east_adjacency": None}},
                                121: {"adjacencies": {"eastern_adjacency": None,
                                                     "western_adjacency": None,
                                                     "southern_adjacency": 122,
                                                     "northern_adjacency": 120,
                                                     "south_east_adjacency": None,
                                                     "south_west_adjacency": None,
                                                     "north_west_adjacency": None,
                                                     "north_east_adjacency": None}},
                                122: {"adjacencies": {"eastern_adjacency": None,
                                                     "western_adjacency": None,
                                                     "southern_adjacency": 123,
                                                     "northern_adjacency": 121,
                                                     "south_east_adjacency": None,
                                                     "south_west_adjacency": None,
                                                     "north_west_adjacency": None,
                                                     "north_east_adjacency": None}},
                                123: {"adjacencies": {"eastern_adjacency": None,
                                                     "western_adjacency": None,
                                                     "southern_adjacency": 124,
                                                     "northern_adjacency": 122,
                                                     "south_east_adjacency": None,
                                                     "south_west_adjacency": None,
                                                     "north_west_adjacency": None,
                                                     "north_east_adjacency": None}},
                                124: {"adjacencies": {"eastern_adjacency": None,
                                                     "western_adjacency": None,
                                                     "southern_adjacency": 125,
                                                     "northern_adjacency": 123,
                                                     "south_east_adjacency": None,
                                                     "south_west_adjacency": None,
                                                     "north_west_adjacency": None,
                                                     "north_east_adjacency": None}},
                                125: {"adjacencies": {"eastern_adjacency": None,
                                                     "western_adjacency": None,
                                                     "southern_adjacency": None,
                                                     "northern_adjacency": 124,
                                                     "south_east_adjacency": None,
                                                     "south_west_adjacency": None,
                                                     "north_west_adjacency": None,
                                                     "north_east_adjacency": None}},
                                126: {"adjacencies": {"eastern_adjacency": None,
                                                      "western_adjacency": None,
                                                      "southern_adjacency": None,
                                                      "northern_adjacency": None,
                                                      "south_east_adjacency": None,
                                                      "south_west_adjacency": None,
                                                      "north_west_adjacency": None,
                                                      "north_east_adjacency": None}},
                                127: {"adjacencies": {"eastern_adjacency": None,
                                                      "western_adjacency": None,
                                                      "southern_adjacency": 128,
                                                      "northern_adjacency": None,
                                                      "south_east_adjacency": None,
                                                      "south_west_adjacency": None,
                                                      "north_west_adjacency": None,
                                                      "north_east_adjacency": None}},
                                128: {"adjacencies": {"eastern_adjacency": None,
                                                      "western_adjacency": None,
                                                      "southern_adjacency": None,
                                                      "northern_adjacency": 127,
                                                      "south_east_adjacency": None,
                                                      "south_west_adjacency": None,
                                                      "north_west_adjacency": None,
                                                      "north_east_adjacency": None}}}

import json

with open("unified_id_and_adjacency_ids.json", "w") as f:
    json.dump(unified_id_and_adjacency_ids, f, indent=4)


cam_to_orient_consideration = {"cam_1": {"east": list(range(50, 55)) + list(range(79, 83)),
                                         "west": list(range(39, 46)) + list(range(71, 76)) + list(range(95, 100)),
                                         "north": list(range(60, 64)) + list(range(87, 90)) + list(range(111, 114)) + list(range(119, 126)) + [127],
                                         "north_east": list(range(55, 60)) + list(range(83, 87)) + list(range(107, 111)),
                                         "north_west": list(range(64, 71)) + list(range(90, 95)) + list(range(114, 119))},
                               "cam_2": {"east": list(range(28, 33)) + list(range(55, 60)),
                                         "west": list(range(35, 39)) + list(range(64, 71)),
                                         "south": list(range(21, 24)) + list(range(46, 50)),
                                         "south_west": list(range(16, 20)) + list(range(39, 46)),
                                         "south_east": list(range(23, 28)) + list(range(50, 55))},
                               "cam_3": {"west": list(range(71, 82)) + list(range(84, 95)) + list(range(95, 106)) + list(range(108, 119)),
                                         "south_west": list(range(71, 82)),
                                         "north_west": list(range(108, 119))}}
