#Image id 0 - cam 4

pa_order_in_json_to_unified_id = dict(zip(range(3, 10, 2), range(48, 52)))
pa_order_in_json_to_unified_id.update(dict(zip(range(8, 0, -2), range(52, 56))))
pa_order_in_json_to_unified_id.update({1: 56})
pa_order_in_json_to_unified_id.update(dict(zip(range(10, 13), range(73, 76))))
pa_order_in_json_to_unified_id.update(dict(zip(range(13, 16, 2), range(76, 78))))
pa_order_in_json_to_unified_id.update(dict(zip(range(16, 13, -2), range(78, 80))))

#Image id 1 - cam 1

pa_order_in_json_to_unified_id.update(dict(zip(range(17, 25), range(0, 8))))
pa_order_in_json_to_unified_id.update(dict(zip(range(25, 33), range(8, 17))))
pa_order_in_json_to_unified_id.update(dict(zip(range(33, 41), range(16, 24))))
pa_order_in_json_to_unified_id.update(dict(zip(range(41, 44, 2), range(24, 26))))
pa_order_in_json_to_unified_id.update({42: 26})
pa_order_in_json_to_unified_id.update(dict(zip(range(44, 48), range(27, 31))))

# Image id 2 - cam 2

pa_order_in_json_to_unified_id.update(dict(zip(range(48, 51), range(5, 8))))
pa_order_in_json_to_unified_id.update(dict(zip(range(51, 55), range(8, 12))))
pa_order_in_json_to_unified_id.update(dict(zip(range(55, 63), range(16, 24))))
pa_order_in_json_to_unified_id.update(dict(zip(range(63, 70), range(24, 31))))
pa_order_in_json_to_unified_id.update(dict(zip(range(70, 73, 2), range(31, 33))))
pa_order_in_json_to_unified_id.update({71: 33})
pa_order_in_json_to_unified_id.update(dict(zip(range(73, 81), range(34, 42))))
pa_order_in_json_to_unified_id.update(dict(zip(range(81, 92), range(62, 73))))

# Image id 3 - cam 3

pa_order_in_json_to_unified_id.update(dict(zip(range(92, 103), range(41, 52))))
pa_order_in_json_to_unified_id.update(dict(zip(range(103, 115), range(52, 64))))
pa_order_in_json_to_unified_id.update(dict(zip(range(115, 118), range(73, 76))))
pa_order_in_json_to_unified_id.update(dict(zip(range(118, 120), range(76, 78))))
pa_order_in_json_to_unified_id.update(dict(zip(range(120, 122), range(78, 80))))

pa_cam_to_space_id = {"cam_1": list(range(17, 48)),
                      "cam_2": list(range(48, 92)),
                      "cam_3": list(range(92, 122)),
                      "cam_4": list(range(1, 17))}

pa_cam_to_unified_id = {k: list(map(lambda x: pa_order_in_json_to_unified_id[x], v)) for k, v in pa_cam_to_space_id.items()}

pa_unified_id_and_adjacency_ids = {0: {"adjacencies": {"eastern_adjacency": 1,
                                                         "western_adjacency": None,
                                                         "southern_adjacency": None,
                                                         "northern_adjacency": 15,
                                                         "south_east_adjacency": None,
                                                         "south_west_adjacency": None,
                                                       "north_west_adjacency": None,
                                                       "north_east_adjacency": 14}},
                                   1: {"adjacencies": {"eastern_adjacency": 2,
                                                         "western_adjacency": 0,
                                                         "southern_adjacency": None,
                                                         "northern_adjacency": 14,
                                                         "south_east_adjacency": None,
                                                         "south_west_adjacency": None,
                                                         "north_west_adjacency": 15,
                                                         "north_east_adjacency": 13}},
                                   2: {"adjacencies": {"eastern_adjacency": 3,
                                                         "western_adjacency": 1,
                                                         "southern_adjacency": None,
                                                         "northern_adjacency": 13,
                                                         "south_east_adjacency": None,
                                                         "south_west_adjacency": None,
                                                         "north_west_adjacency": 14,
                                                         "north_east_adjacency": 12}},
                                   3: {"adjacencies": {"eastern_adjacency": 4,
                                                         "western_adjacency": 2,
                                                         "southern_adjacency": None,
                                                         "northern_adjacency": 12,
                                                         "south_east_adjacency": None,
                                                         "south_west_adjacency": None,
                                                         "north_west_adjacency": 13,
                                                         "north_east_adjacency": 11}},
                                   4: {"adjacencies": {"eastern_adjacency": 5,
                                                         "western_adjacency": 3,
                                                         "southern_adjacency": None,
                                                         "northern_adjacency": 11,
                                                         "south_east_adjacency": None,
                                                         "south_west_adjacency": None,
                                                         "north_west_adjacency": 12,
                                                         "north_east_adjacency": 10}},
                                   5: {"adjacencies": {"eastern_adjacency": 6,
                                                         "western_adjacency": 4,
                                                         "southern_adjacency": None,
                                                         "northern_adjacency": 10,
                                                         "south_east_adjacency": None,
                                                         "south_west_adjacency": None,
                                                         "north_west_adjacency": 11,
                                                         "north_east_adjacency": 9}},
                                   6: {"adjacencies": {"eastern_adjacency": 7,
                                                         "western_adjacency": 5,
                                                         "southern_adjacency": None,
                                                         "northern_adjacency": 9,
                                                         "south_east_adjacency": None,
                                                         "south_west_adjacency": None,
                                                         "north_west_adjacency": 10,
                                                         "north_east_adjacency": 8}},
                                   7: {"adjacencies": {"eastern_adjacency": None,
                                                         "western_adjacency": 6,
                                                         "southern_adjacency": None,
                                                         "northern_adjacency": 8,
                                                         "south_east_adjacency": None,
                                                         "south_west_adjacency": None,
                                                         "north_west_adjacency": 9,
                                                         "north_east_adjacency": None}},
                                   8: {"adjacencies": {"eastern_adjacency": None,
                                                         "western_adjacency": 9,
                                                         "southern_adjacency": 7,
                                                         "northern_adjacency": None,
                                                         "south_east_adjacency": None,
                                                         "south_west_adjacency": 6,
                                                         "north_west_adjacency": None,
                                                         "north_east_adjacency": None}},
                                   9: {"adjacencies": {"eastern_adjacency": 8,
                                                         "western_adjacency": 10,
                                                         "southern_adjacency": 6,
                                                         "northern_adjacency": None,
                                                         "south_east_adjacency": 7,
                                                         "south_west_adjacency": 5,
                                                         "north_west_adjacency": None,
                                                         "north_east_adjacency": None}},
                                   10: {"adjacencies": {"eastern_adjacency": 9,
                                                          "western_adjacency": 11,
                                                          "southern_adjacency": 5,
                                                          "northern_adjacency": None,
                                                          "south_east_adjacency": 6,
                                                          "south_west_adjacency": 4,
                                                          "north_west_adjacency": None,
                                                          "north_east_adjacency": None}},
                                   11: {"adjacencies": {"eastern_adjacency": 10,
                                                          "western_adjacency": 12,
                                                          "southern_adjacency": 4,
                                                          "northern_adjacency": None,
                                                          "south_east_adjacency": 5,
                                                          "south_west_adjacency": 3,
                                                          "north_west_adjacency": None,
                                                          "north_east_adjacency": None}},
                                   12: {"adjacencies": {"eastern_adjacency": 11,
                                                          "western_adjacency": 13,
                                                          "southern_adjacency": 3,
                                                          "northern_adjacency": None,
                                                          "south_east_adjacency": 4,
                                                          "south_west_adjacency": 2,
                                                          "north_west_adjacency": None,
                                                          "north_east_adjacency": None}},
                                   13: {"adjacencies": {"eastern_adjacency": 12,
                                                          "western_adjacency": 14,
                                                          "southern_adjacency": 2,
                                                          "northern_adjacency": None,
                                                          "south_east_adjacency": 3,
                                                          "south_west_adjacency": 1,
                                                          "north_west_adjacency": None,
                                                          "north_east_adjacency": None}},
                                   14: {"adjacencies": {"eastern_adjacency": 13,
                                                          "western_adjacency": 15,
                                                          "southern_adjacency": 1,
                                                          "northern_adjacency": None,
                                                          "south_east_adjacency": 2,
                                                          "south_west_adjacency": 0,
                                                          "north_west_adjacency": None,
                                                          "north_east_adjacency": None}},
                                   15: {"adjacencies": {"eastern_adjacency": 14,
                                                          "western_adjacency": None,
                                                          "southern_adjacency": 0,
                                                          "northern_adjacency": None,
                                                          "south_east_adjacency": 1,
                                                          "south_west_adjacency": None,
                                                          "north_west_adjacency": None,
                                                          "north_east_adjacency": None}},
                                   16: {"adjacencies": {"eastern_adjacency": 17,
                                                          "western_adjacency": None,
                                                          "southern_adjacency": None,
                                                          "northern_adjacency": None,
                                                          "south_east_adjacency": None,
                                                          "south_west_adjacency": None,
                                                          "north_west_adjacency": None,
                                                          "north_east_adjacency": 30}},
                                   17: {"adjacencies": {"eastern_adjacency": 18,
                                                          "western_adjacency": 16,
                                                          "southern_adjacency": None,
                                                          "northern_adjacency": 30,
                                                          "south_east_adjacency": None,
                                                          "south_west_adjacency": None,
                                                          "north_west_adjacency": None,
                                                          "north_east_adjacency": 29}},
                                   18: {"adjacencies": {"eastern_adjacency": 19,
                                                          "western_adjacency": 17,
                                                          "southern_adjacency": None,
                                                          "northern_adjacency": 29,
                                                          "south_east_adjacency": None,
                                                          "south_west_adjacency": None,
                                                          "north_west_adjacency": 30,
                                                          "north_east_adjacency": 28}},
                                   19: {"adjacencies": {"eastern_adjacency": 20,
                                                          "western_adjacency": 18,
                                                          "southern_adjacency": None,
                                                          "northern_adjacency": 28,
                                                          "south_east_adjacency": None,
                                                          "south_west_adjacency": None,
                                                          "north_west_adjacency": 29,
                                                          "north_east_adjacency": 27}},
                                   20: {"adjacencies": {"eastern_adjacency": 21,
                                                          "western_adjacency": 19,
                                                          "southern_adjacency": None,
                                                          "northern_adjacency": 27,
                                                          "south_east_adjacency": None,
                                                          "south_west_adjacency": None,
                                                          "north_west_adjacency": 28,
                                                          "north_east_adjacency": 26}},
                                   21: {"adjacencies": {"eastern_adjacency": 22,
                                                          "western_adjacency": 20,
                                                          "southern_adjacency": None,
                                                          "northern_adjacency": 26,
                                                          "south_east_adjacency": None,
                                                          "south_west_adjacency": None,
                                                          "north_west_adjacency": 27,
                                                          "north_east_adjacency": 25}},
                                   22: {"adjacencies": {"eastern_adjacency": 23,
                                                          "western_adjacency": 21,
                                                          "southern_adjacency": None,
                                                          "northern_adjacency": 25,
                                                          "south_east_adjacency": None,
                                                          "south_west_adjacency": None,
                                                          "north_west_adjacency": 26,
                                                          "north_east_adjacency": 24}},
                                   23: {"adjacencies": {"eastern_adjacency": None,
                                                          "western_adjacency": 22,
                                                          "southern_adjacency": None,
                                                          "northern_adjacency": 24,
                                                          "south_east_adjacency": None,
                                                          "south_west_adjacency": None,
                                                          "north_west_adjacency": 25,
                                                          "north_east_adjacency": None}},
                                   24: {"adjacencies": {"eastern_adjacency": None,
                                                          "western_adjacency": 25,
                                                          "southern_adjacency": 23,
                                                          "northern_adjacency": None,
                                                          "south_east_adjacency": None,
                                                          "south_west_adjacency": None,
                                                          "north_west_adjacency": 22,
                                                          "north_east_adjacency": None}},
                                   25: {"adjacencies": {"eastern_adjacency": 24,
                                                          "western_adjacency": 26,
                                                          "southern_adjacency": 22,
                                                          "northern_adjacency": None,
                                                          "south_east_adjacency": 23,
                                                          "south_west_adjacency": 21,
                                                          "north_west_adjacency": None,
                                                          "north_east_adjacency": None}},
                                   26: {"adjacencies": {"eastern_adjacency": 25,
                                                          "western_adjacency": 27,
                                                          "southern_adjacency": 21,
                                                          "northern_adjacency": None,
                                                          "south_east_adjacency": 22,
                                                          "south_west_adjacency": 20,
                                                          "north_west_adjacency": None,
                                                          "north_east_adjacency": None}},
                                   27: {"adjacencies": {"eastern_adjacency": 26,
                                                          "western_adjacency": 27,
                                                          "southern_adjacency": 20,
                                                          "northern_adjacency": None,
                                                          "south_east_adjacency": 21,
                                                          "south_west_adjacency": 19,
                                                          "north_west_adjacency": None,
                                                          "north_east_adjacency": None}},
                                   28: {"adjacencies": {"eastern_adjacency": 27,
                                                          "western_adjacency": 29,
                                                          "southern_adjacency": 19,
                                                          "northern_adjacency": None,
                                                          "south_east_adjacency": 20,
                                                          "south_west_adjacency": 18,
                                                          "north_west_adjacency": None,
                                                          "north_east_adjacency": None}},
                                   29: {"adjacencies": {"eastern_adjacency": 28,
                                                          "western_adjacency": 30,
                                                          "southern_adjacency": 18,
                                                          "northern_adjacency": None,
                                                          "south_east_adjacency": 19,
                                                          "south_west_adjacency": 17,
                                                          "north_west_adjacency": None,
                                                          "north_east_adjacency": None}},
                                   30: {"adjacencies": {"eastern_adjacency": 29,
                                                          "western_adjacency": None,
                                                          "southern_adjacency": 17,
                                                          "northern_adjacency": None,
                                                          "south_east_adjacency": 18,
                                                          "south_west_adjacency": 16,
                                                          "north_west_adjacency": None,
                                                          "north_east_adjacency": None}},
                                   31: {"adjacencies": {"eastern_adjacency": 32,
                                                          "western_adjacency": None,
                                                          "southern_adjacency": None,
                                                          "northern_adjacency": 72,
                                                          "south_east_adjacency": None,
                                                          "south_west_adjacency": None,
                                                          "north_west_adjacency": None,
                                                          "north_east_adjacency": 71}},
                                   32: {"adjacencies": {"eastern_adjacency": 33,
                                                          "western_adjacency": 31,
                                                          "southern_adjacency": None,
                                                          "northern_adjacency": 71,
                                                          "south_east_adjacency": None,
                                                          "south_west_adjacency": None,
                                                          "north_west_adjacency": 72,
                                                          "north_east_adjacency": 70}},
                                   33: {"adjacencies": {"eastern_adjacency": 34,
                                                          "western_adjacency": 32,
                                                          "southern_adjacency": None,
                                                          "northern_adjacency": 70,
                                                          "south_east_adjacency": None,
                                                          "south_west_adjacency": None,
                                                          "north_west_adjacency": 71,
                                                          "north_east_adjacency": 69}},
                                   34: {"adjacencies": {"eastern_adjacency": 35,
                                                          "western_adjacency": 33,
                                                          "southern_adjacency": None,
                                                          "northern_adjacency": 69,
                                                          "south_east_adjacency": None,
                                                          "south_west_adjacency": None,
                                                          "north_west_adjacency": 70,
                                                          "north_east_adjacency": 68}},
                                   35: {"adjacencies": {"eastern_adjacency": 36,
                                                          "western_adjacency": 34,
                                                          "southern_adjacency": None,
                                                          "northern_adjacency": 68,
                                                          "south_east_adjacency": None,
                                                          "south_west_adjacency": None,
                                                          "north_west_adjacency": 69,
                                                          "north_east_adjacency": 67}},
                                   36: {"adjacencies": {"eastern_adjacency": 37,
                                                          "western_adjacency": 35,
                                                          "southern_adjacency": None,
                                                          "northern_adjacency": 67,
                                                          "south_east_adjacency": None,
                                                          "south_west_adjacency": None,
                                                          "north_west_adjacency": 68,
                                                          "north_east_adjacency": 66}},
                                   37: {"adjacencies": {"eastern_adjacency": 38,
                                                          "western_adjacency": 36,
                                                          "southern_adjacency": None,
                                                          "northern_adjacency": 66,
                                                          "south_east_adjacency": None,
                                                          "south_west_adjacency": None,
                                                          "north_west_adjacency": 67,
                                                          "north_east_adjacency": 65}},
                                   38: {"adjacencies": {"eastern_adjacency": 39,
                                                          "western_adjacency": 37,
                                                          "southern_adjacency": None,
                                                          "northern_adjacency": 65,
                                                          "south_east_adjacency": None,
                                                          "south_west_adjacency": None,
                                                          "north_west_adjacency": 66,
                                                          "north_east_adjacency": 64}},
                                   39: {"adjacencies": {"eastern_adjacency": 40,
                                                          "western_adjacency": 38,
                                                          "southern_adjacency": None,
                                                          "northern_adjacency": 64,
                                                          "south_east_adjacency": None,
                                                          "south_west_adjacency": None,
                                                          "north_west_adjacency": 65,
                                                          "north_east_adjacency": 63}},
                                   40: {"adjacencies": {"eastern_adjacency": 41,
                                                          "western_adjacency": 39,
                                                          "southern_adjacency": None,
                                                          "northern_adjacency": 63,
                                                          "south_east_adjacency": None,
                                                          "south_west_adjacency": None,
                                                          "north_west_adjacency": 64,
                                                          "north_east_adjacency": 62}},
                                   41: {"adjacencies": {"eastern_adjacency": 42,
                                                          "western_adjacency": 40,
                                                          "southern_adjacency": None,
                                                          "northern_adjacency": 62,
                                                          "south_east_adjacency": None,
                                                          "south_west_adjacency": None,
                                                          "north_west_adjacency": 63,
                                                          "north_east_adjacency": 64}},
                                   42: {"adjacencies": {"eastern_adjacency": 43,
                                                          "western_adjacency": 41,
                                                          "southern_adjacency": None,
                                                          "northern_adjacency": 61,
                                                          "south_east_adjacency": None,
                                                          "south_west_adjacency": None,
                                                          "north_west_adjacency": 62,
                                                          "north_east_adjacency": 60}},
                                   43: {"adjacencies": {"eastern_adjacency": 44,
                                                          "western_adjacency": 42,
                                                          "southern_adjacency": None,
                                                          "northern_adjacency": 60,
                                                          "south_east_adjacency": None,
                                                          "south_west_adjacency": None,
                                                          "north_west_adjacency": 61,
                                                          "north_east_adjacency": 59}},
                                   44: {"adjacencies": {"eastern_adjacency": 45,
                                                          "western_adjacency": 43,
                                                          "southern_adjacency": None,
                                                          "northern_adjacency": 59,
                                                          "south_east_adjacency": None,
                                                          "south_west_adjacency": None,
                                                          "north_west_adjacency": 60,
                                                          "north_east_adjacency": 58}},
                                   45: {"adjacencies": {"eastern_adjacency": 46,
                                                          "western_adjacency": 44,
                                                          "southern_adjacency": None,
                                                          "northern_adjacency": 58,
                                                          "south_east_adjacency": None,
                                                          "south_west_adjacency": None,
                                                          "north_west_adjacency": 59,
                                                          "north_east_adjacency": 57}},
                                   46: {"adjacencies": {"eastern_adjacency": 47,
                                                          "western_adjacency": 45,
                                                          "southern_adjacency": None,
                                                          "northern_adjacency": 57,
                                                          "south_east_adjacency": None,
                                                          "south_west_adjacency": None,
                                                          "north_west_adjacency": 58,
                                                          "north_east_adjacency": 56}},
                                   47: {"adjacencies": {"eastern_adjacency": 48,
                                                          "western_adjacency": 46,
                                                          "southern_adjacency": None,
                                                          "northern_adjacency": 56,
                                                          "south_east_adjacency": None,
                                                          "south_west_adjacency": None,
                                                          "north_west_adjacency": 57,
                                                          "north_east_adjacency": 55}},
                                   48: {"adjacencies": {"eastern_adjacency": 49,
                                                          "western_adjacency": 47,
                                                          "southern_adjacency": None,
                                                          "northern_adjacency": 55,
                                                          "south_east_adjacency": None,
                                                          "south_west_adjacency": None,
                                                          "north_west_adjacency": 56,
                                                          "north_east_adjacency": 54}},
                                   49: {"adjacencies": {"eastern_adjacency": 50,
                                                          "western_adjacency": 48,
                                                          "southern_adjacency": None,
                                                          "northern_adjacency": 54,
                                                          "south_east_adjacency": None,
                                                          "south_west_adjacency": None,
                                                          "north_west_adjacency": 55,
                                                          "north_east_adjacency": 53}},
                                   50: {"adjacencies": {"eastern_adjacency": 51,
                                                          "western_adjacency": 49,
                                                          "southern_adjacency": None,
                                                          "northern_adjacency": 53,
                                                          "south_east_adjacency": None,
                                                          "south_west_adjacency": None,
                                                          "north_west_adjacency": 54,
                                                          "north_east_adjacency": 52}},
                                   51: {"adjacencies": {"eastern_adjacency": None,
                                                          "western_adjacency": 50,
                                                          "southern_adjacency": None,
                                                          "northern_adjacency": 52,
                                                          "south_east_adjacency": None,
                                                          "south_west_adjacency": None,
                                                          "north_west_adjacency": 53,
                                                          "north_east_adjacency": None}},
                                   52: {"adjacencies": {"eastern_adjacency": None,
                                                          "western_adjacency": 53,
                                                          "southern_adjacency": 51,
                                                          "northern_adjacency": None,
                                                          "south_east_adjacency": None,
                                                          "south_west_adjacency": 50,
                                                          "north_west_adjacency": None,
                                                          "north_east_adjacency": 73}},
                                   53: {"adjacencies": {"eastern_adjacency": 52,
                                                          "western_adjacency": 54,
                                                          "southern_adjacency": 50,
                                                          "northern_adjacency": None,
                                                          "south_east_adjacency": None,
                                                          "south_west_adjacency": 49,
                                                          "north_west_adjacency": None,
                                                          "north_east_adjacency": 51}},
                                   54: {"adjacencies": {"eastern_adjacency": 53,
                                                          "western_adjacency": 55,
                                                          "southern_adjacency": 49,
                                                          "northern_adjacency": None,
                                                          "south_east_adjacency": None,
                                                          "south_west_adjacency": 48,
                                                          "north_west_adjacency": None,
                                                          "north_east_adjacency": 50}},
                                   55: {"adjacencies": {"eastern_adjacency": 54,
                                                          "western_adjacency": 56,
                                                          "southern_adjacency": 48,
                                                          "northern_adjacency": None,
                                                          "south_east_adjacency": None,
                                                          "south_west_adjacency": 47,
                                                          "north_west_adjacency": None,
                                                          "north_east_adjacency": 49}},
                                   56: {"adjacencies": {"eastern_adjacency": 55,
                                                          "western_adjacency": 57,
                                                          "southern_adjacency": 47,
                                                          "northern_adjacency": None,
                                                          "south_east_adjacency": None,
                                                          "south_west_adjacency": 46,
                                                          "north_west_adjacency": None,
                                                          "north_east_adjacency": 48}},
                                   57: {"adjacencies": {"eastern_adjacency": 56,
                                                          "western_adjacency": 58,
                                                          "southern_adjacency": 46,
                                                          "northern_adjacency": None,
                                                          "south_east_adjacency": None,
                                                          "south_west_adjacency": 45,
                                                          "north_west_adjacency": None,
                                                          "north_east_adjacency": 47}},
                                   58: {"adjacencies": {"eastern_adjacency": 57,
                                                          "western_adjacency": 59,
                                                          "southern_adjacency": 45,
                                                          "northern_adjacency": None,
                                                          "south_east_adjacency": None,
                                                          "south_west_adjacency": 44,
                                                          "north_west_adjacency": None,
                                                          "north_east_adjacency": 46}},
                                   59: {"adjacencies": {"eastern_adjacency": 58,
                                                          "western_adjacency": 60,
                                                          "southern_adjacency": 44,
                                                          "northern_adjacency": None,
                                                          "south_east_adjacency": None,
                                                          "south_west_adjacency": 43,
                                                          "north_west_adjacency": None,
                                                          "north_east_adjacency": 45}},
                                   60: {"adjacencies": {"eastern_adjacency": 59,
                                                          "western_adjacency": 61,
                                                          "southern_adjacency": 43,
                                                          "northern_adjacency": None,
                                                          "south_east_adjacency": None,
                                                          "south_west_adjacency": 42,
                                                          "north_west_adjacency": None,
                                                          "north_east_adjacency": 44}},
                                   61: {"adjacencies": {"eastern_adjacency": 60,
                                                          "western_adjacency": 62,
                                                          "southern_adjacency": 42,
                                                          "northern_adjacency": None,
                                                          "south_east_adjacency": None,
                                                          "south_west_adjacency": 41,
                                                          "north_west_adjacency": None,
                                                          "north_east_adjacency": 43}},
                                   62: {"adjacencies": {"eastern_adjacency": 61,
                                                          "western_adjacency": 63,
                                                          "southern_adjacency": 41,
                                                          "northern_adjacency": None,
                                                          "south_east_adjacency": None,
                                                          "south_west_adjacency": 40,
                                                          "north_west_adjacency": None,
                                                          "north_east_adjacency": 42}},
                                   63: {"adjacencies": {"eastern_adjacency": 62,
                                                          "western_adjacency": 64,
                                                          "southern_adjacency": 40,
                                                          "northern_adjacency": None,
                                                          "south_east_adjacency": None,
                                                          "south_west_adjacency": 39,
                                                          "north_west_adjacency": None,
                                                          "north_east_adjacency": 41}},
                                   64: {"adjacencies": {"eastern_adjacency": 63,
                                                          "western_adjacency": 65,
                                                          "southern_adjacency": 39,
                                                          "northern_adjacency": None,
                                                          "south_east_adjacency": None,
                                                          "south_west_adjacency": 38,
                                                          "north_west_adjacency": None,
                                                          "north_east_adjacency": 40}},
                                   65: {"adjacencies": {"eastern_adjacency": 64,
                                                          "western_adjacency": 66,
                                                          "southern_adjacency": 38,
                                                          "northern_adjacency": None,
                                                          "south_east_adjacency": None,
                                                          "south_west_adjacency": 37,
                                                          "north_west_adjacency": None,
                                                          "north_east_adjacency": 39}},
                                   66: {"adjacencies": {"eastern_adjacency": 65,
                                                          "western_adjacency": 67,
                                                          "southern_adjacency": 37,
                                                          "northern_adjacency": None,
                                                          "south_east_adjacency": None,
                                                          "south_west_adjacency": 36,
                                                          "north_west_adjacency": None,
                                                          "north_east_adjacency": 38}},
                                   67: {"adjacencies": {"eastern_adjacency": 66,
                                                          "western_adjacency": 68,
                                                          "southern_adjacency": 36,
                                                          "northern_adjacency": None,
                                                          "south_east_adjacency": None,
                                                          "south_west_adjacency": 35,
                                                          "north_west_adjacency": None,
                                                          "north_east_adjacency": 37}},
                                   68: {"adjacencies": {"eastern_adjacency": 67,
                                                          "western_adjacency": 69,
                                                          "southern_adjacency": 35,
                                                          "northern_adjacency": None,
                                                          "south_east_adjacency": None,
                                                          "south_west_adjacency": 34,
                                                          "north_west_adjacency": None,
                                                          "north_east_adjacency": 36}},
                                   69: {"adjacencies": {"eastern_adjacency": 68,
                                                          "western_adjacency": 70,
                                                          "southern_adjacency": 34,
                                                          "northern_adjacency": None,
                                                          "south_east_adjacency": None,
                                                          "south_west_adjacency": 33,
                                                          "north_west_adjacency": None,
                                                          "north_east_adjacency": 35}},
                                   70: {"adjacencies": {"eastern_adjacency": 69,
                                                          "western_adjacency": 71,
                                                          "southern_adjacency": 33,
                                                          "northern_adjacency": None,
                                                          "south_east_adjacency": None,
                                                          "south_west_adjacency": 32,
                                                          "north_west_adjacency": None,
                                                          "north_east_adjacency": 34}},
                                   71: {"adjacencies": {"eastern_adjacency": 70,
                                                          "western_adjacency": 72,
                                                          "southern_adjacency": 32,
                                                          "northern_adjacency": None,
                                                          "south_east_adjacency": None,
                                                          "south_west_adjacency": 31,
                                                          "north_west_adjacency": None,
                                                          "north_east_adjacency": 33}},
                                   72: {"adjacencies": {"eastern_adjacency": 71,
                                                          "western_adjacency": None,
                                                          "southern_adjacency": 31,
                                                          "northern_adjacency": None,
                                                          "south_east_adjacency": None,
                                                          "south_west_adjacency": None,
                                                          "north_west_adjacency": None,
                                                          "north_east_adjacency": 32}},
                                   73: {"adjacencies": {"eastern_adjacency": 74,
                                                          "western_adjacency": None,
                                                          "southern_adjacency": None,
                                                          "northern_adjacency": None,
                                                          "south_east_adjacency": None,
                                                          "south_west_adjacency": 52,
                                                          "north_west_adjacency": None,
                                                          "north_east_adjacency": None}},
                                   74: {"adjacencies": {"eastern_adjacency": 75,
                                                          "western_adjacency": 73,
                                                          "southern_adjacency": None,
                                                          "northern_adjacency": None,
                                                          "south_east_adjacency": None,
                                                          "south_west_adjacency": None,
                                                          "north_west_adjacency": None,
                                                          "north_east_adjacency": None}},
                                   75: {"adjacencies": {"eastern_adjacency": None,
                                                          "western_adjacency": 74,
                                                          "southern_adjacency": None,
                                                          "northern_adjacency": None,
                                                          "south_east_adjacency": None,
                                                          "south_west_adjacency": None,
                                                          "north_west_adjacency": None,
                                                          "north_east_adjacency": None}},
                                   76: {"adjacencies": {"eastern_adjacency": 79,
                                                          "western_adjacency": None,
                                                          "southern_adjacency": 77,
                                                          "northern_adjacency": None,
                                                          "south_east_adjacency": 78,
                                                          "south_west_adjacency": None,
                                                          "north_west_adjacency": None,
                                                          "north_east_adjacency": None}},
                                   77: {"adjacencies": {"eastern_adjacency": 78,
                                                          "western_adjacency": None,
                                                          "southern_adjacency": None,
                                                          "northern_adjacency": 76,
                                                          "south_east_adjacency": 78,
                                                          "south_west_adjacency": None,
                                                          "north_west_adjacency": None,
                                                          "north_east_adjacency": 79}},
                                   78: {"adjacencies": {"eastern_adjacency": None,
                                                          "western_adjacency": 77,
                                                          "southern_adjacency": None,
                                                          "northern_adjacency": 79,
                                                          "south_east_adjacency": None,
                                                          "south_west_adjacency": None,
                                                          "north_west_adjacency": 76,
                                                          "north_east_adjacency": None}},
                                   79: {"adjacencies": {"eastern_adjacency": None,
                                                          "western_adjacency": 76,
                                                          "southern_adjacency": 78,
                                                          "northern_adjacency": None,
                                                          "south_east_adjacency": None,
                                                          "south_west_adjacency": 77,
                                                          "north_west_adjacency": None,
                                                          "north_east_adjacency": None}},
                                   }

pa_cam_to_orient_consideration = {"cam_1": {"west": list(range(0, 7)) + list(range(9, 16)) + list(range(16, 23)) + list(range(25, 31)),
                                            "north_west": list(range(9, 16)) + list(range(25, 31)),
                                            "north": [24]},
                                  "cam_2": {"west": list(range(5, 7)) + list(range(9, 12)) + list(range(16, 23)) + list(range(25, 31)),
                                            "north_west": list(range(9, 12)) + list(range(25, 31)),
                                            "north": [24, 72],
                                            "east": list(range(32, 42)) + list(range(62, 72)),
                                            "north_east": list(range(62, 72))},
                                  "cam_3": {"west": list(range(41, 44)) + list(range(60, 64)),
                                            "nort_west": list(range(59, 64)),
                                            "north": list(range(56, 60)),
                                            "east": list(range(46, 52)) + list(range(52, 58)) + list(range(73, 76)) + [76, 79],
                                            "north_east": list(range(52, 58)) + list(range(73, 76)) + [79]},
                                  "cam_4": {"west": list(range(48, 51)) + list(range(53, 57)),
                                            "north_west": list(range(53, 57)),
                                            "north": [52, 76],
                                            "east": list(range(78, 80)),
                                            "north_east": [79]}}

pa_unified_id_to_orientation_consideration = {}
for unified_id in range(80):
    pa_unified_id_to_orientation_consideration[unified_id] = {}
    for cam in pa_cam_to_orient_consideration:
        pa_unified_id_to_orientation_consideration[unified_id][cam] = list()
        for orient in pa_cam_to_orient_consideration[cam]:
            if unified_id in pa_cam_to_orient_consideration[cam][orient]:
                pa_unified_id_to_orientation_consideration[unified_id][cam].append(orient)
        if len(pa_unified_id_to_orientation_consideration[unified_id][cam]) == 0:
            pa_unified_id_to_orientation_consideration[unified_id].pop(cam)